spring.application.name=uni_transport_system
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BusTransportSystem;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourStrongPassword

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Frontend Static Resources
spring.web.resources.static-locations=classpath:/static/