spring.application.name=uni_transport_system
# MS SQL Server configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=utms_db;encrypt=true;trustServerCertificate=true;integratedSecurity=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.datasource.url=jdbc:h2:mem:utms_db;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
# spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration